#!/bin/bash
# generate-bat.sh - CRLF-safe .bat generator for Chrome WSL Bridge
# Generates chrome-native-host.bat with CRLF line endings, logging, and error handling
# Usage: generate-bat.sh [--check]

set -euo pipefail

# Auto-detect Windows username
detect_win_user() {
    local win_user
    win_user=$(cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n')
    if [ -z "$win_user" ]; then
        echo "Error: Could not detect Windows username" >&2
        exit 1
    fi
    echo "$win_user"
}

# Auto-detect WSL home
detect_wsl_home() {
    echo "$HOME"
}

WIN_USER=$(detect_win_user)
WSL_HOME=$(detect_wsl_home)
WIN_CHROME_DIR="/mnt/c/Users/${WIN_USER}/.claude/chrome"
BAT_PATH="${WIN_CHROME_DIR}/chrome-native-host.bat"

check_crlf() {
    local target="${1:-$BAT_PATH}"
    if [ ! -f "$target" ]; then
        echo "Error: File does not exist: $target" >&2
        exit 1
    fi
    if file "$target" | grep -q "CRLF"; then
        echo "PASS: ${target} has CRLF line endings"
        exit 0
    else
        echo "FAIL: ${target} does NOT have CRLF line endings" >&2
        exit 1
    fi
}

generate_bat() {
    local tmp_path="${BAT_PATH}.tmp"
    local win_log_path="C:\\Users\\${WIN_USER}\\.claude\\chrome\\bridge.log"
    local wsl_wrapper_path="${WSL_HOME}/.claude/chrome/chrome-native-host"

    # Backup original .bat if it exists
    if [ -f "$BAT_PATH" ]; then
        cp -p "$BAT_PATH" "${BAT_PATH}.bak"
        echo "Backed up original .bat to ${BAT_PATH}.bak"
    fi

    # Write .bat content with CRLF line endings using printf
    # Each line ends with \r\n for proper CRLF
    printf '@echo off\r\n' > "$tmp_path"
    printf 'REM Chrome Native Host WSL Bridge - generated by generate-bat.sh\r\n' >> "$tmp_path"
    printf 'REM Pre-flight check: verify wsl.exe exists\r\n' >> "$tmp_path"
    printf 'where wsl.exe >nul 2>&1\r\n' >> "$tmp_path"
    printf 'if %%ERRORLEVEL%% neq 0 (\r\n' >> "$tmp_path"
    printf '    echo %%DATE%% %%TIME%% ERROR: wsl.exe not found >> "%s"\r\n' "$win_log_path" >> "$tmp_path"
    printf '    exit /b 1\r\n' >> "$tmp_path"
    printf ')\r\n' >> "$tmp_path"
    printf 'echo %%DATE%% %%TIME%% invoked >> "%s"\r\n' "$win_log_path" >> "$tmp_path"
    printf 'C:\\Windows\\system32\\wsl.exe --exec %s\r\n' "$wsl_wrapper_path" >> "$tmp_path"
    printf 'echo %%DATE%% %%TIME%% exitcode=%%ERRORLEVEL%% >> "%s"\r\n' "$win_log_path" >> "$tmp_path"
    printf 'exit /b %%ERRORLEVEL%%\r\n' >> "$tmp_path"

    # Validate CRLF on the temp file
    if file "$tmp_path" | grep -q "CRLF"; then
        mv "$tmp_path" "$BAT_PATH"
        echo "Generated: ${BAT_PATH}"
        echo "CRLF validation: PASS"
    else
        rm -f "$tmp_path"
        echo "Error: Generated .bat file failed CRLF validation. Temp file removed." >&2
        exit 1
    fi
}

# Main
if [ $# -eq 0 ]; then
    generate_bat
elif [ "$1" = "--check" ]; then
    check_crlf "${2:-$BAT_PATH}"
else
    echo "Usage: $0 [--check [file]]" >&2
    exit 1
fi
