#!/bin/bash
# version-wrapper.sh - Generate dynamic version wrapper for Chrome Native Host
# Generates a POSIX-compatible wrapper that auto-detects the latest Claude Code version
# Usage: version-wrapper.sh [--dry-run]

set -euo pipefail

VERSIONS_DIR="$HOME/.local/share/claude/versions"
CHROME_DIR="$HOME/.claude/chrome"
WRAPPER_PATH="${CHROME_DIR}/chrome-native-host"
LAST_VERSION_FILE="${CHROME_DIR}/last-known-version.txt"

# Find the highest semver directory in versions dir
find_latest_version() {
    local latest=""
    if [ ! -d "$VERSIONS_DIR" ]; then
        return 1
    fi
    # List version files, sort by semver, pick highest
    latest=$(ls -1 "$VERSIONS_DIR" 2>/dev/null | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)
    if [ -z "$latest" ]; then
        return 1
    fi
    echo "$latest"
}

dry_run() {
    local version
    version=$(find_latest_version) || {
        echo "No version directories found in ${VERSIONS_DIR}" >&2
        # Try fallback
        if [ -f "$LAST_VERSION_FILE" ]; then
            echo "Fallback version: $(cat "$LAST_VERSION_FILE")"
        else
            echo "No fallback version available either" >&2
            exit 1
        fi
        return
    }
    echo "Detected version: ${version}"
    echo "Binary path: ${VERSIONS_DIR}/${version}"
    echo "Wrapper would be written to: ${WRAPPER_PATH}"
}

generate_wrapper() {
    local version
    version=$(find_latest_version) || {
        echo "Error: No version directories found in ${VERSIONS_DIR}" >&2
        exit 1
    }

    # Backup original wrapper if it exists and no backup exists yet
    if [ -f "$WRAPPER_PATH" ] && [ ! -f "${WRAPPER_PATH}.bak" ]; then
        cp -p "$WRAPPER_PATH" "${WRAPPER_PATH}.bak"
        echo "Backed up original wrapper to ${WRAPPER_PATH}.bak"
    elif [ -f "$WRAPPER_PATH" ]; then
        # Always update the backup to reflect the state before this generation
        cp -p "$WRAPPER_PATH" "${WRAPPER_PATH}.bak"
    fi

    # Write the dynamic wrapper script (POSIX-compatible)
    cat > "$WRAPPER_PATH" << 'WRAPPER_EOF'
#!/bin/sh
# Chrome native host wrapper script - dynamic version detection
# Generated by version-wrapper.sh - do not edit manually

VERSIONS_DIR="$HOME/.local/share/claude/versions"
LAST_VERSION_FILE="$HOME/.claude/chrome/last-known-version.txt"
LOG_FILE="$HOME/.claude/chrome/bridge.log"

# Find highest semver version
find_version() {
    if [ -d "$VERSIONS_DIR" ]; then
        ls -1 "$VERSIONS_DIR" 2>/dev/null | sort -t. -k1,1n -k2,2n -k3,3n | tail -1
    fi
}

VERSION=$(find_version)

if [ -z "$VERSION" ]; then
    # No versions found, try fallback
    if [ -f "$LAST_VERSION_FILE" ]; then
        VERSION=$(cat "$LAST_VERSION_FILE")
        if [ ! -f "${VERSIONS_DIR}/${VERSION}" ]; then
            echo "Error: Fallback version ${VERSION} no longer exists" >&2
            echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR: No valid version found, fallback ${VERSION} missing" >> "$LOG_FILE" 2>/dev/null
            exit 1
        fi
    else
        echo "Error: No Claude Code versions found and no fallback available" >&2
        echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR: No versions found, no fallback" >> "$LOG_FILE" 2>/dev/null
        exit 1
    fi
fi

BINARY="${VERSIONS_DIR}/${VERSION}"

if [ ! -f "$BINARY" ]; then
    # Current version missing but others may exist - already handled by find_version
    echo "Error: Binary not found: ${BINARY}" >&2
    echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR: Binary not found: ${BINARY}" >> "$LOG_FILE" 2>/dev/null
    exit 1
fi

# Record successful version for fallback
echo "$VERSION" > "$LAST_VERSION_FILE" 2>/dev/null

exec "$BINARY" --chrome-native-host
WRAPPER_EOF

    chmod +x "$WRAPPER_PATH"

    # Record current version
    echo "$version" > "$LAST_VERSION_FILE"

    echo "Generated dynamic wrapper at: ${WRAPPER_PATH}"
    echo "Current version: ${version}"
    echo "Fallback recorded in: ${LAST_VERSION_FILE}"
}

# Main
if [ $# -eq 0 ]; then
    generate_wrapper
elif [ "$1" = "--dry-run" ]; then
    dry_run
else
    echo "Usage: $0 [--dry-run]" >&2
    exit 1
fi
